<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>stringrule</name>
  <uuid>3556391e-f14f-48f5-b034-8fffbc9ebc40</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Input is 11/25/2020 9:00:00 PM +0000
then
    set decision to "Eat" ;
else 
    set decision to "Don't Eat" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
